# Desactivar por completo el inicio de fuentes de datos fijas
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Configurar el puerto dinámico obligatorio para Azure
server.port=${PORT:8080}